### ISSUE TITLE
Issue when trying to run hubot-twitter-subscriptions

### ISSUE THREAD

**Issue by downright770** [alindeman/hubot-twitter-stream#3]
Hi,
I'm still abit new to coding and using hubot.
I've set up a shell script to export cmds for 

#export HUBOT_TWITTER_CONSUMER_KEY=
#export HUBOT_TWITTER_CONSUMER_SECRET=
#export HUBOT_TWITTER_ACCESS_TOKEN=
#export HUBOT_TWITTER_ACCESS_TOKEN_SECRET=

When running the script I get.

[Tue Dec 06 2016 15:40:12 GMT-0800 (PST)] ERROR Error loading scripts from npm package - Error: Cannot find module 'hubot-twitter-subsciptions'
  at Function.Module._resolveFilename (module.js:469:15)
  at Function.Module._load (module.js:417:25)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at Robot.loadExternalScripts (/home/chat/mybot/node_modules/hubot/src/robot.coffee:401:11, <js>:272:27)
  at /home/chat/mybot/node_modules/hubot/bin/hubot:152:11, <js>:159:26
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)

Any help would be great thank you.

**Comment by downright770** [comment]
Fixed the first issue that was my bad was a spelling mistake in my external scripts.

but now getting 

[Wed Dec 07 2016 09:03:11 GMT-0800 (PST)] ERROR twitter-subscriptions: Missing Twitter configuration variables. Not loading.

**Comment by downright770** [comment]
I was able to get through the first issue but running into a different error now.
I checked to see if redis would ping and that seems to be working.

[Wed Dec 07 2016 09:31:16 GMT-0800 (PST)] INFO twitter-subscriptions: There are no subscriptions to load from radis brain.
[Wed Dec 07 2016 09:31:16 GMT-0800 (PST)] ERROR TypeError: Converting circular structure to JSON
  at Object.stringify (native)
  at Brain.<anonymous> (/home/chat/mybot/node_modules/hubot-twitter-subscriptions/src/twitter-stream.coffee:83:13, <js>:120:65)
  at emitOne (events.js:101:20)
  at Brain.emit (events.js:188:7)
  at Brain.mergeData (/home/chat/mybot/node_modules/hubot/src/brain.coffee:92:5, <js>:82:19)
  at /home/chat/mybot/node_modules/hubot-redis-brain/src/redis-brain.coffee:49:9, <js>:28:23
  at try_callback (/home/chat/mybot/node_modules/redis/index.js:548:9)
  at RedisClient.return_reply (/home/chat/mybot/node_modules/redis/index.js:630:13)
  at ReplyParser.<anonymous> (/home/chat/mybot/node_modules/redis/index.js:282:14)
  at emitOne (events.js:96:13)
  at ReplyParser.emit (events.js:188:7)
  at ReplyParser.send_reply (/home/chat/mybot/node_modules/redis/lib/parser/javascript.js:300:10)
  at ReplyParser.execute (/home/chat/mybot/node_modules/redis/lib/parser/javascript.js:203:22)
  at RedisClient.on_data (/home/chat/mybot/node_modules/redis/index.js:504:27)
  at Socket.<anonymous> (/home/chat/mybot/node_modules/redis/index.js:82:14)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at readableAddChunk (_stream_readable.js:176:18)
  at Socket.Readable.push (_stream_readable.js:134:10)
  at TCP.onread (net.js:548:20)
